# Generated by Django 5.2.4 on 2026-09-19 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0003_user_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyIDMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_table', models.CharField(help_text="BizNet table name, lowercase, e.g. 'products'", max_length=64)),
                ('source_pk', models.CharField(help_text='BizNet primary key as text, e.g. ProductID/PartyID/SaleID', max_length=64)),
                ('target_app_label', models.CharField(max_length=64)),
                ('target_model', models.CharField(max_length=64)),
                ('target_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_id_maps', to='user_auth.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'source_table', 'target_id'], name='data_migrat_company_f218a5_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'source_table', 'source_pk'), name='uniq_legacy_source_row')],
            },
        ),
    ]
