# Generated by Django 5.2.4 on 2026-08-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorddeletionlog',
            name='action',
            field=models.CharField(choices=[('deleted', 'Deleted'), ('restored', 'Restored'), ('purged', 'Purged'), ('edited', 'Edited')], max_length=10),
        ),
    ]
