# Generated by Django 5.2.4 on 2026-08-09 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_recorddeletionlog_action'),
        ('user_auth', '0002_user_deleted_at_user_deleted_by_user_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_request_id', models.CharField(max_length=100)),
                ('response_status', models.PositiveSmallIntegerField()),
                ('response_body', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to='user_auth.company')),
            ],
            options={
                'unique_together': {('company', 'client_request_id')},
            },
        ),
    ]
