# Generated by Django 5.2.4 on 2026-08-10 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_idempotencykey'),
        ('user_auth', '0002_user_deleted_at_user_deleted_by_user_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_key', models.CharField(max_length=64)),
                ('next_value', models.PositiveIntegerField(default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_sequences', to='user_auth.company')),
            ],
            options={
                'unique_together': {('company', 'sequence_key')},
            },
        ),
    ]
