# Generated by Django 5.2.4 on 2026-08-12 06:51

import core.device_registry
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_numbersequence'),
        ('user_auth', '0003_user_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceIdRangeCounter',
            fields=[
                ('id', models.PositiveIntegerField(default=1, primary_key=True, serialize=False)),
                ('next_range_start', models.BigIntegerField(default=10000000000)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(default=core.device_registry._new_device_id, max_length=64, unique=True)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('range_start', models.BigIntegerField()),
                ('range_end', models.BigIntegerField()),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('revoked', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desktop_devices', to='user_auth.company')),
            ],
        ),
    ]
