# Generated by Django 5.2.4 on 2026-08-12 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_device_registry'),
        ('user_auth', '0003_user_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopSyncQueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_request_id', models.CharField(max_length=64, unique=True)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('payload_json', models.TextField()),
                ('response_json', models.TextField(blank=True)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desktop_sync_queue_entries', to='user_auth.company')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
