# Generated by Django 5.2.4 on 2026-08-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_desktop_sync_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktopsyncqueueentry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed'), ('discarded', 'Discarded')], default='pending', max_length=10),
        ),
    ]
