# Generated by Django 5.2.4 on 2026-08-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sync_queue_discarded_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopDeviceIdentity',
            fields=[
                ('id', models.PositiveIntegerField(default=1, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=64)),
                ('range_start', models.BigIntegerField()),
                ('range_end', models.BigIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
