# Generated by Django 5.2.4 on 2026-08-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_desktopdeviceidentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorddeletionlog',
            name='object_id',
            field=models.PositiveBigIntegerField(),
        ),
    ]
