# Generated by Django 5.2.4 on 2026-08-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_recorddeletionlog_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbersequence',
            name='next_value',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
