# Generated by Django 5.2.4 on 2025-07-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqitem',
            name='maximum_qty_acceptable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rfqitem',
            name='minimum_qty_required',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='rfqitem',
            name='required_uom',
            field=models.CharField(blank=True, help_text='Required UOM for quotation', max_length=50),
        ),
        migrations.AddField(
            model_name='rfqitem',
            name='target_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='supplierquotationitem',
            name='base_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per base unit (auto-calculated)', max_digits=12),
        ),
        migrations.AddField(
            model_name='supplierquotationitem',
            name='minimum_order_qty',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='supplierquotationitem',
            name='package_qty',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Quantity of base units in this UOM (e.g., 10 pieces per packet)', max_digits=10),
        ),
        migrations.AddField(
            model_name='supplierquotationitem',
            name='quoted_uom',
            field=models.CharField(blank=True, help_text='UOM as quoted by supplier', max_length=50),
        ),
        migrations.AddField(
            model_name='supplierquotationitem',
            name='total_base_units',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total base units for quoted quantity', max_digits=15),
        ),
    ]
