# Generated by Django 5.2.4 on 2025-07-27 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('purchase', '0002_rfqitem_maximum_qty_acceptable_and_more'),
        ('user_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='grnitem',
            old_name='accepted_quantity',
            new_name='accepted_qty',
        ),
        migrations.RenameField(
            model_name='grnitem',
            old_name='rejected_quantity',
            new_name='ordered_qty',
        ),
        migrations.RenameField(
            model_name='grnitem',
            old_name='received_quantity',
            new_name='received_qty',
        ),
        migrations.RenameField(
            model_name='grnitem',
            old_name='quality_notes',
            new_name='remarks',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='delivery_address',
            new_name='terms_conditions',
        ),
        migrations.RenameField(
            model_name='requestforquotation',
            old_name='due_date',
            new_name='response_deadline',
        ),
        migrations.RenameField(
            model_name='supplierquotationitem',
            old_name='lead_time_days',
            new_name='delivery_time_days',
        ),
        migrations.RenameField(
            model_name='supplierquotationitem',
            old_name='discount_percentage',
            new_name='item_discount_percentage',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='supplierquotation',
            name='lead_time_days',
        ),
        migrations.AddField(
            model_name='bill',
            name='approval_documents',
            field=models.FileField(blank=True, help_text='Internal approval documents', null=True, upload_to='purchase/bills/approvals/'),
        ),
        migrations.AddField(
            model_name='bill',
            name='supplier_invoice',
            field=models.FileField(blank=True, help_text='Supplier invoice document', null=True, upload_to='purchase/bills/invoices/'),
        ),
        migrations.AddField(
            model_name='bill',
            name='supporting_documents',
            field=models.FileField(blank=True, help_text='Supporting documents (receipts, etc.)', null=True, upload_to='purchase/bills/supporting/'),
        ),
        migrations.AddField(
            model_name='bill',
            name='tax_invoice',
            field=models.FileField(blank=True, help_text='Tax invoice document', null=True, upload_to='purchase/bills/tax/'),
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='delivery_challan',
            field=models.FileField(blank=True, help_text='Supplier delivery challan', null=True, upload_to='purchase/grn/challan/'),
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='gate_entry_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='inspected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_grns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='inspection_report',
            field=models.FileField(blank=True, help_text='Internal quality inspection report', null=True, upload_to='purchase/grn/inspection/'),
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='packing_list',
            field=models.FileField(blank=True, help_text='Packing list document', null=True, upload_to='purchase/grn/packing/'),
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='photos_received_goods',
            field=models.FileField(blank=True, help_text='Photos of received goods', null=True, upload_to='purchase/grn/photos/'),
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='quality_certificates',
            field=models.FileField(blank=True, help_text='Quality certificates from supplier', null=True, upload_to='purchase/grn/quality/'),
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='total_received_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='rejected_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='amendment_documents',
            field=models.FileField(blank=True, help_text='PO amendments or revisions', null=True, upload_to='purchase/orders/amendments/'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_terms',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('amount', 'Fixed Amount'), ('per_item', 'Per Item')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_limit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum allowed purchase amount', max_digits=15),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_order_document',
            field=models.FileField(blank=True, help_text='Generated PO document', null=True, upload_to='purchase/orders/'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_agreement',
            field=models.FileField(blank=True, help_text='Supplier agreement/contract', null=True, upload_to='purchase/orders/agreements/'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='technical_drawings',
            field=models.FileField(blank=True, help_text='Technical drawings or specifications', null=True, upload_to='purchase/orders/drawings/'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Delivery warehouse', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='item_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='quotation_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.supplierquotationitem'),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='bank_statement',
            field=models.FileField(blank=True, help_text='Bank statement showing payment', null=True, upload_to='purchase/payments/statements/'),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='check_copy',
            field=models.FileField(blank=True, help_text='Copy of check if payment by check', null=True, upload_to='purchase/payments/checks/'),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='payment_receipt',
            field=models.FileField(blank=True, help_text='Payment receipt document', null=True, upload_to='purchase/payments/receipts/'),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='wire_transfer_advice',
            field=models.FileField(blank=True, help_text='Wire transfer advice document', null=True, upload_to='purchase/payments/wire/'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='budget_approval',
            field=models.FileField(blank=True, help_text='Budget approval document', null=True, upload_to='purchase/requisitions/budget/'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='requisition_document',
            field=models.FileField(blank=True, help_text='Requisition document', null=True, upload_to='purchase/requisitions/'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='technical_specifications',
            field=models.FileField(blank=True, help_text='Technical specifications', null=True, upload_to='purchase/requisitions/specs/'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Delivery warehouse', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='photos_returned_items',
            field=models.FileField(blank=True, help_text='Photos of returned items', null=True, upload_to='purchase/returns/photos/'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='quality_report',
            field=models.FileField(blank=True, help_text='Quality inspection report for return', null=True, upload_to='purchase/returns/quality/'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='return_authorization',
            field=models.FileField(blank=True, help_text='Return authorization document', null=True, upload_to='purchase/returns/authorization/'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='supplier_acknowledgment',
            field=models.FileField(blank=True, help_text='Supplier acknowledgment of return', null=True, upload_to='purchase/returns/acknowledgment/'),
        ),
        migrations.AddField(
            model_name='requestforquotation',
            name='delivery_terms',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='requestforquotation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requestforquotation',
            name='drawing_attachments',
            field=models.FileField(blank=True, help_text='Technical drawings or blueprints', null=True, upload_to='purchase/rfq/drawings/'),
        ),
        migrations.AddField(
            model_name='requestforquotation',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='requestforquotation',
            name='rfq_document',
            field=models.FileField(blank=True, help_text='RFQ document file', null=True, upload_to='purchase/rfq/'),
        ),
        migrations.AddField(
            model_name='requestforquotation',
            name='technical_specifications',
            field=models.FileField(blank=True, help_text='Technical specifications document', null=True, upload_to='purchase/rfq/specs/'),
        ),
        migrations.AddField(
            model_name='requestforquotation',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Delivery warehouse', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='rfqitem',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='agreement_contract',
            field=models.FileField(blank=True, help_text='Master agreement or contract', null=True, upload_to='purchase/suppliers/contracts/'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_documents',
            field=models.FileField(blank=True, help_text='Bank account verification documents', null=True, upload_to='purchase/suppliers/bank/'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='quality_certificates',
            field=models.FileField(blank=True, help_text='Quality certifications (ISO, etc.)', null=True, upload_to='purchase/suppliers/quality/'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='registration_certificate',
            field=models.FileField(blank=True, help_text='Business registration certificate', null=True, upload_to='purchase/suppliers/registration/'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tax_certificate',
            field=models.FileField(blank=True, help_text='Tax registration certificate', null=True, upload_to='purchase/suppliers/tax/'),
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='certificate_documents',
            field=models.FileField(blank=True, help_text='Quality certificates, compliance docs', null=True, upload_to='purchase/quotations/certificates/'),
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='delivery_time_days',
            field=models.IntegerField(default=0, help_text='Delivery time in days'),
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('amount', 'Fixed Amount'), ('per_item', 'Per Item')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='price_list',
            field=models.FileField(blank=True, help_text='Supplier price list', null=True, upload_to='purchase/quotations/pricelists/'),
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='quotation_document',
            field=models.FileField(blank=True, help_text='Supplier quotation document', null=True, upload_to='purchase/quotations/'),
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='technical_brochure',
            field=models.FileField(blank=True, help_text='Product technical brochure', null=True, upload_to='purchase/quotations/brochures/'),
        ),
        migrations.AddField(
            model_name='supplierquotationitem',
            name='item_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='supplierquotationitem',
            name='rfq_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_quotation_items', to='purchase.rfqitem'),
        ),
        migrations.AddField(
            model_name='supplierquotationitem',
            name='specifications',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='goodsreceiptnote',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('received', 'Received'), ('inspected', 'Inspected'), ('completed', 'Completed')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='grnitem',
            name='quality_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('partial', 'Partial')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('sent_to_supplier', 'Sent to Supplier'), ('acknowledged', 'Acknowledged'), ('partially_received', 'Partially Received'), ('fully_received', 'Fully Received'), ('cancelled', 'Cancelled')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='requestforquotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('responses_received', 'Responses Received'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='draft', max_length=50),
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=20)),
                ('uom_type', models.CharField(choices=[('weight', 'Weight'), ('volume', 'Volume'), ('length', 'Length'), ('area', 'Area'), ('quantity', 'Quantity'), ('time', 'Time')], max_length=50)),
                ('is_base_unit', models.BooleanField(default=False, help_text='Base unit for this UOM type')),
                ('conversion_factor', models.DecimalField(decimal_places=6, default=1, help_text='Conversion factor to base unit', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_uoms', to='user_auth.company')),
            ],
            options={
                'ordering': ['uom_type', 'name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='grnitem',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.unitofmeasure'),
        ),
        migrations.AlterField(
            model_name='rfqitem',
            name='required_uom',
            field=models.ForeignKey(blank=True, help_text='Required UOM for quotation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.unitofmeasure'),
        ),
        migrations.AlterField(
            model_name='supplierquotationitem',
            name='quoted_uom',
            field=models.ForeignKey(blank=True, help_text='UOM as quoted by supplier', null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.unitofmeasure'),
        ),
    ]
