# Generated by Django 5.2.4 on 2025-07-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_rename_accepted_quantity_grnitem_accepted_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierquotation',
            name='discount_application',
            field=models.CharField(choices=[('subtract', 'Subtract from Total (Discount)'), ('add', 'Add to Total (Rebate/Fee)')], default='subtract', help_text='Whether to subtract (discount) or add (rebate/fee) to total', max_length=20),
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='minimum_order_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum order value requirement', max_digits=15),
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='quantity_discount_min_qty',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum quantity for quantity-based discount', max_digits=10),
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='quantity_discount_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount rate for quantity-based discount', max_digits=5),
        ),
        migrations.AddField(
            model_name='supplierquotationitem',
            name='item_discount_application',
            field=models.CharField(choices=[('subtract', 'Subtract (Discount)'), ('add', 'Add (Rebate/Fee)')], default='subtract', help_text='Whether to subtract or add to item total', max_length=20),
        ),
        migrations.AddField(
            model_name='supplierquotationitem',
            name='item_discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount'), ('quantity_based', 'Quantity Based')], default='percentage', help_text='Type of discount/rebate applied to this item', max_length=20),
        ),
        migrations.AddField(
            model_name='supplierquotationitem',
            name='item_qty_discount_min',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum quantity for item quantity discount', max_digits=10),
        ),
        migrations.AddField(
            model_name='supplierquotationitem',
            name='item_qty_discount_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount rate for quantity-based discount', max_digits=5),
        ),
        migrations.AlterField(
            model_name='supplierquotation',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed discount/rebate amount (negative for rebate, positive for discount)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='supplierquotation',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage discount/rebate (negative for rebate, positive for discount)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='supplierquotation',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage Discount/Rebate'), ('fixed_amount', 'Fixed Amount Discount/Rebate'), ('quantity_based', 'Quantity Based Discount/Rebate')], default='percentage', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplierquotationitem',
            name='item_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Item-specific fixed discount/rebate amount', max_digits=12),
        ),
        migrations.AlterField(
            model_name='supplierquotationitem',
            name='item_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Item-specific percentage discount/rebate', max_digits=5),
        ),
        migrations.AlterField(
            model_name='supplierquotationitem',
            name='minimum_order_qty',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Minimum order quantity as specified by supplier', max_digits=10),
        ),
    ]
