# Generated by Django 5.2.4 on 2025-07-28 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_remove_grnitem_tracking_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsreceiptnote',
            name='total_received_value',
        ),
        migrations.RemoveField(
            model_name='grnitem',
            name='total_value',
        ),
        migrations.RemoveField(
            model_name='grnitem',
            name='unit_price',
        ),
    ]
