# Generated by Django 5.2.4 on 2025-07-29 22:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_remove_goodsreceiptnote_total_received_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='grn_match_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='has_additional_items',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='has_quantity_variances',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='matching_type',
            field=models.CharField(choices=[('three_way', 'Three-Way Match (PO + GRN + Invoice)'), ('two_way_po', 'Two-Way Match (PO + Invoice)'), ('two_way_grn', 'Two-Way Match (GRN + Invoice)'), ('manual', 'Manual Entry (No Match)')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='bill',
            name='po_match_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billitem',
            name='grn_quantity_variance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='billitem',
            name='is_additional_item',
            field=models.BooleanField(default=False, help_text='Item not in PO/GRN'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='item_source',
            field=models.CharField(choices=[('po', 'From Purchase Order'), ('grn', 'From GRN'), ('manual', 'Manual Entry')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='billitem',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='billitem',
            name='po_quantity_variance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='billitem',
            name='tracking_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billitem',
            name='tracking_type',
            field=models.CharField(choices=[('none', 'No Tracking'), ('batch', 'Batch/Lot Tracking'), ('serial', 'Serial Number'), ('imei', 'IMEI Number'), ('barcode', 'Barcode Tracking'), ('expiry', 'Expiry Date Tracking')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='billitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='grninventorylock',
            name='is_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grninventorylock',
            name='released_for_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_locks', to='purchase.bill'),
        ),
        migrations.CreateModel(
            name='BillItemTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(help_text='Serial, IMEI, Barcode, etc.', max_length=100)),
                ('tracking_type', models.CharField(choices=[('none', 'No Tracking'), ('batch', 'Batch/Lot Tracking'), ('serial', 'Serial Number'), ('imei', 'IMEI Number'), ('barcode', 'Barcode Tracking'), ('expiry', 'Expiry Date Tracking')], max_length=20)),
                ('creates_asset', models.BooleanField(default=False, help_text='Whether this item creates a fixed asset')),
                ('asset_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_items', to='purchase.billitem')),
                ('grn_tracking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.grnitemtracking')),
            ],
            options={
                'unique_together': {('bill_item', 'tracking_number')},
            },
        ),
    ]
