# Generated by Django 5.2.4 on 2025-07-29 22:26

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_bill_grn_match_status_bill_has_additional_items_and_more'),
        ('user_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('reference_type', models.CharField(choices=[('bill', 'Purchase Bill/Invoice'), ('payment', 'Payment Made'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note'), ('advance', 'Advance Payment'), ('adjustment', 'Manual Adjustment'), ('opening_balance', 'Opening Balance')], max_length=50)),
                ('reference_id', models.IntegerField(help_text='ID of the referenced document')),
                ('description', models.TextField()),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount owed TO supplier', max_digits=15)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount paid BY company', max_digits=15)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Running balance', max_digits=15)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='actual_date',
            field=models.DateField(blank=True, help_text='Actual payment date', null=True),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='advance_adjusted',
            field=models.BooleanField(default=False, help_text='Has advance been adjusted against bills?'),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='approval_code',
            field=models.CharField(blank=True, help_text='Approval code for card payments', max_length=100),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='approval_document',
            field=models.FileField(blank=True, help_text='Payment approval document', null=True, upload_to='purchase/payments/approvals/'),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='bank_account',
            field=models.CharField(blank=True, help_text='Bank account used for payment', max_length=255),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='base_currency_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='beneficiary_bank',
            field=models.CharField(blank=True, help_text="Supplier's bank details", max_length=255),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='expected_date',
            field=models.DateField(blank=True, help_text='Expected payment date', null=True),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Internal notes not visible to supplier'),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='is_advance',
            field=models.BooleanField(default=False, help_text='Is this an advance payment?'),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='payment_type',
            field=models.CharField(choices=[('bill_payment', 'Bill Payment'), ('advance_payment', 'Advance Payment'), ('partial_payment', 'Partial Payment'), ('refund', 'Refund'), ('credit_note', 'Credit Note Application'), ('adjustment', 'Adjustment')], default='bill_payment', max_length=50),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='swift_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Bank transaction ID', max_length=255),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='purchase.bill'),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='payment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('check', 'Check'), ('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('online', 'Online Payment'), ('credit_note', 'Credit Note'), ('advance', 'Advance Payment')], default='bank_transfer', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Bank reference, check number, etc.', max_length=255),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='purchase.supplier'),
        ),
        migrations.AddIndex(
            model_name='purchasepayment',
            index=models.Index(fields=['supplier', 'payment_date'], name='purchase_pu_supplie_8d7ba4_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasepayment',
            index=models.Index(fields=['status', 'payment_date'], name='purchase_pu_status_d2a364_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasepayment',
            index=models.Index(fields=['payment_type', 'created_at'], name='purchase_pu_payment_acf11d_idx'),
        ),
        migrations.AddField(
            model_name='supplierledger',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_ledgers', to='user_auth.company'),
        ),
        migrations.AddField(
            model_name='supplierledger',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierledger',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='purchase.supplier'),
        ),
        migrations.AddIndex(
            model_name='supplierledger',
            index=models.Index(fields=['supplier', 'transaction_date'], name='purchase_su_supplie_9b8220_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierledger',
            index=models.Index(fields=['reference_type', 'reference_id'], name='purchase_su_referen_28132c_idx'),
        ),
    ]
