# Generated by Django 5.2.4 on 2025-07-29 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('products', '0003_alter_producttracking_unique_together_and_more'),
        ('purchase', '0009_supplierledger_purchasepayment_actual_date_and_more'),
        ('user_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('primary', 'Primary Contact'), ('accounting', 'Accounting'), ('sales', 'Sales'), ('technical', 'Technical Support'), ('logistics', 'Logistics'), ('quality', 'Quality Assurance'), ('executive', 'Executive'), ('other', 'Other')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('mobile', models.CharField(blank=True, max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['supplier', 'contact_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierProductCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_product_code', models.CharField(blank=True, max_length=100)),
                ('supplier_product_name', models.CharField(blank=True, max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('INR', 'Indian Rupee'), ('CNY', 'Chinese Yuan')], default='USD', max_length=3)),
                ('minimum_order_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('lead_time_days', models.IntegerField(default=0)),
                ('tier_1_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tier_1_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tier_2_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tier_2_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tier_3_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tier_3_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('effective_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('technical_specifications', models.TextField(blank=True)),
                ('warranty_terms', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['supplier', 'product'],
            },
        ),
        migrations.AddField(
            model_name='supplier',
            name='annual_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='business_registration_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='certifications',
            field=models.TextField(blank=True, help_text='ISO, quality certifications, etc.'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='compliance_documents',
            field=models.FileField(blank=True, help_text='Compliance and regulatory documents', null=True, upload_to='purchase/suppliers/compliance/'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='credit_period_days',
            field=models.IntegerField(default=30, help_text='Credit period in days'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='employee_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='established_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='insurance_certificate',
            field=models.FileField(blank=True, help_text='Insurance certificate', null=True, upload_to='purchase/suppliers/insurance/'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='last_contact_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='minimum_order_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='supplier',
            name='mobile',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='supplier',
            name='next_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True, help_text='General notes about the supplier'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='overall_rating',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Overall rating 0-10', max_digits=3),
        ),
        migrations.AddField(
            model_name='supplier',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='preferred_currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('INR', 'Indian Rupee'), ('CNY', 'Chinese Yuan')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='supplier',
            name='preferred_shipping_method',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='price_rating',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price competitiveness 0-10', max_digits=3),
        ),
        migrations.AddField(
            model_name='supplier',
            name='relationship_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_suppliers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplier',
            name='service_rating',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Service rating 0-10', max_digits=3),
        ),
        migrations.AddField(
            model_name='supplier',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending_approval', 'Pending Approval'), ('blacklisted', 'Blacklisted'), ('on_hold', 'On Hold'), ('terminated', 'Terminated')], default='active', max_length=50),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_type',
            field=models.CharField(choices=[('manufacturer', 'Manufacturer'), ('distributor', 'Distributor'), ('wholesaler', 'Wholesaler'), ('retailer', 'Retailer'), ('service_provider', 'Service Provider'), ('contractor', 'Contractor'), ('consultant', 'Consultant'), ('other', 'Other')], default='manufacturer', max_length=50),
        ),
        migrations.AddField(
            model_name='supplier',
            name='vat_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='payment_terms',
            field=models.CharField(choices=[('net_15', 'Net 15'), ('net_30', 'Net 30'), ('net_45', 'Net 45'), ('net_60', 'Net 60'), ('net_90', 'Net 90'), ('cash_on_delivery', 'Cash on Delivery'), ('advance_payment', 'Advance Payment'), ('30_60_90', '30% Advance, 70% on Delivery'), ('2_10_net_30', '2/10 Net 30'), ('custom', 'Custom Terms')], default='net_30', max_length=50),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['supplier_code'], name='purchase_su_supplie_420db2_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['status', 'is_active'], name='purchase_su_status_88c818_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['supplier_type'], name='purchase_su_supplie_afaba2_idx'),
        ),
        migrations.AddField(
            model_name='suppliercontact',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='purchase.supplier'),
        ),
        migrations.AddField(
            model_name='supplierproductcatalog',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_catalogs', to='products.product'),
        ),
        migrations.AddField(
            model_name='supplierproductcatalog',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_catalog', to='purchase.supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='supplierproductcatalog',
            unique_together={('supplier', 'product')},
        ),
    ]
