# Generated by Django 5.2.4 on 2026-08-02 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stocklot_quarantine_reason'),
        ('purchase', '0011_alter_supplier_options_remove_supplier_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Receiving warehouse for manual (no-GRN) bills', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='inventory.warehouse'),
        ),
    ]
