# Generated by Django 5.2.4 on 2026-08-02 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_brand_producttracking_battery_health_and_more'),
        ('purchase', '0012_bill_warehouse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='goods_received',
            field=models.BooleanField(default=True, help_text='False = invoice recorded but goods not yet physically received/scanned in'),
        ),
        migrations.AddField(
            model_name='bill',
            name='receipt_notes',
            field=models.TextField(blank=True, help_text='Optional note added when confirming goods received'),
        ),
        migrations.AddField(
            model_name='bill',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_bills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariant'),
        ),
    ]
