# Generated by Django 5.2.4 on 2026-08-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0014_bill_deleted_at_bill_deleted_by_bill_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Whole-bill quick discount, applied on top of any per-line discounts', max_digits=15),
        ),
        migrations.AddField(
            model_name='billitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='billitem',
            name='discounts',
            field=models.JSONField(blank=True, default=list, help_text='[{"type": "fixed"|"percent"|"per_unit", "value": "10.00"}, ...]'),
        ),
    ]
