# Generated by Django 5.2.4 on 2026-08-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0015_bill_discount_amount_billitem_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='received_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='How much of this line has actually been scanned/received via bill_receive_items() so far - bill_receive_items() rejects receiving past `quantity`.', max_digits=10),
        ),
    ]
