# Generated by Django 5.2.4 on 2026-08-11 01:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0017_supplierledgeradjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierledgeradjustment',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
