# Generated by Django 5.2.4 on 2026-08-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0018_alter_supplierledgeradjustment_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitofmeasure',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
