# Generated by Django 5.2.4 on 2026-08-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0019_unitofmeasure_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseapproval',
            name='document_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='supplierledger',
            name='reference_id',
            field=models.BigIntegerField(help_text='ID of the referenced document'),
        ),
    ]
