# Generated by Django 5.2.4 on 2026-08-20 23:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_attribute_updated_at'),
        ('purchase', '0020_alter_purchaseapproval_document_id_and_more'),
        ('user_auth', '0003_user_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('debit_date', models.DateField(default=django.utils.timezone.localdate)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reason', models.CharField(choices=[('return', 'Stock Return'), ('damage', 'Damaged Goods'), ('wrong_item', 'Wrong Item Received'), ('error', 'Billing Error'), ('other', 'Other')], default='return', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_notes', to='purchase.bill')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_notes', to='user_auth.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_debit_notes', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_notes', to='purchase.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='DebitNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bill_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_note_items', to='purchase.billitem')),
                ('debit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.debitnote')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_note_items', to='products.product')),
                ('tracking_unit', models.ForeignKey(blank=True, help_text='Specific IMEI/serial unit being returned - null for untracked/quantity-based items', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_note_items', to='products.producttracking')),
            ],
        ),
    ]
