# Generated by Django 5.2.4 on 2025-08-05 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_employeebenefit_employeerelation_hrpolicy_jobvacancy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='cost_per_participant',
            new_name='cost',
        ),
        migrations.RemoveField(
            model_name='employeerelation',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='salary_max',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='salary_min',
        ),
        migrations.AddField(
            model_name='employeerelation',
            name='title',
            field=models.CharField(default='None', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='qualification_required',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='salary_range',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='training',
            name='training_type',
            field=models.CharField(choices=[('workshop', 'Workshop'), ('seminar', 'Seminar'), ('course', 'Course'), ('conference', 'Conference'), ('webinar', 'Webinar'), ('certification', 'Certification Program'), ('on_job', 'On-the-Job Training'), ('orientation', 'Orientation')], default='workshop', max_length=50),
        ),
        migrations.AlterField(
            model_name='employeerelation',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='application_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='hr.designation'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_vacancies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='responsibilities',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
