# Generated by Django 5.2.4 on 2025-08-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventorylock_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklot',
            name='quarantine_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
