# Generated by Django 5.2.4 on 2026-08-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stocklot_quarantine_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stocklot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stockserial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
