# Generated by Django 5.2.4 on 2026-08-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventorylock_updated_at_stocklot_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylock',
            name='reference_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reference_id',
            field=models.PositiveBigIntegerField(blank=True, help_text='ID of the reference document', null=True),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='reference_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
