"""
Django settings for setting project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
import os
import environ
from pathlib import Path

# Initialize environment variables
env = environ.Env(
    # Set casting, default value
    DEBUG=(bool, True),
    USE_SQLITE=(bool, False),
    VERCEL=(bool, False),
)

# Take environment variables from .env file if it exists
env_file = Path(__file__).resolve().parent.parent / '.env'
if env_file.exists():
    environ.Env.read_env(env_file)
else:
    # Fallback to reading from environment variables only
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY', default='django-insecure-68t(2+%h9$c^ojm#kd%wx^eo0lv4s*(!rt-%bg5n98y!uqa=2d')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DJANGO_DEBUG', default=True)

ALLOWED_HOSTS = env.list('DJANGO_ALLOWED_HOSTS', default=['*'])


# Application definition

INSTALLED_APPS = [
    "unfold",  # before django.contrib.admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    "unfold.contrib.guardian",  # optional, if django-guardian package is used
    "unfold.contrib.simple_history",  # optional, if django-simple-history package is used
    "unfold.contrib.location_field",  # optional, if django-location-field package is used
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user_auth',  # Add user_auth app
    'crm',
    'sales',
    'purchase',
    'inventory',
    'accounting',
    'hr',
    'project_mgmt',
    'manufacturing',
    'core',
    'rest_framework',
    'rest_framework.authtoken',
    'analytics', 
    'products',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add WhiteNoise for static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'user_auth.middleware.ActivityLogMiddleware',  # Activity log middleware
]

ROOT_URLCONF = 'setting.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            os.path.join(BASE_DIR, 'user_auth/templates'),
            os.path.join(BASE_DIR, 'crm/templates'),
            os.path.join(BASE_DIR, 'sales/templates'),
            os.path.join(BASE_DIR, 'purchase/templates'),
            os.path.join(BASE_DIR, 'inventory'),
            os.path.join(BASE_DIR, 'accounting/templates'),
            os.path.join(BASE_DIR, 'hr/templates'),
            os.path.join(BASE_DIR, 'project_mgmt/templates'),
            os.path.join(BASE_DIR, 'manufacturing/templates'),
            os.path.join(BASE_DIR, 'core/templates'),
            ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'setting.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use SQLite for Vercel deployment, PostgreSQL for local development
if env.bool('USE_SQLITE', default=False):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {        
            'ENGINE': env('DB_ENGINE', default='django.db.backends.postgresql'),
            'NAME': env('DB_NAME', default='erp'),
            'USER': env('DB_USER', default='postgres'),
            'PASSWORD': env('DB_PASSWORD', default='password'),
            'HOST': env('DB_HOST', default='localhost'),
            'PORT': env('DB_PORT', default='5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Environment-based configurations
IS_PRODUCTION = env('VERCEL'==True, default=True)

# Create static directories if they don't exist (only in development)
if not IS_PRODUCTION:
    try:
        os.makedirs(STATIC_ROOT, exist_ok=True)
        os.makedirs(os.path.join(BASE_DIR, 'static'), exist_ok=True)
    except OSError:
        # Directory creation failed (e.g., read-only filesystem in production)
        pass

# Enable WhiteNoise for static files
if IS_PRODUCTION:
    # In production, use WhiteNoise for static file serving
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    # Add WhiteNoise configuration for better performance
    WHITENOISE_USE_FINDERS = True
    WHITENOISE_AUTOREFRESH = True
    WHITENOISE_INDEX_FILE = True

    WHITENOISE_ROOT = os.path.join(BASE_DIR, 'staticfiles')
else:
    # In development, use default static files storage
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Celery settings (only for development)
if not IS_PRODUCTION:
    CELERY_BROKER_URL = 'redis://localhost:6379/0'
    CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
    CELERY_ACCEPT_CONTENT = ['json']
    CELERY_TASK_SERIALIZER = 'json'
    CELERY_RESULT_SERIALIZER = 'json'
else:
    # Disable Celery for serverless deployment
    CELERY_BROKER_URL = None

# Security settings for production
if IS_PRODUCTION:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    
    # Session configuration for production
    SESSION_ENGINE = 'django.contrib.sessions.backends.db'
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True

# Logging configuration
if IS_PRODUCTION:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
            },
        },
        'root': {
            'handlers': ['console'],
            'level': 'WARNING',  # Reduce log noise in production
        },
    }
else:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
            },
        },
        'root': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    }

# Cache configuration
if IS_PRODUCTION:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
        }
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'user_auth.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

UNFOLD = {
    "SITE_TITLE": "ERP System",
    "SITE_HEADER": "ERP System Admin",
    "SITE_URL": "/",
    "SITE_ICON": lambda request: static("logo.png"),
    "SITE_LOGO": {
        "light": lambda request: static("logo.png"),
        "dark": lambda request: static("logo.png"),
    },
    "SITE_SYMBOL": "dashboard",
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "sizes": "32x32",
            "type": "image/svg+xml",
            "href": lambda request: static("logo.png"),
        },
    ],
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SHOW_BACK_BUTTON": True,
    "LOGIN": {
        "image": lambda request: static("bg.jpg"),
        "title": "Welcome to ERP System Admin",
        "description": "Please login to access the system",
    },
    "STYLES": [
    ],
    "SCRIPTS": [],
    "COLORS": {
        "base": {
            # Light mode
            "50": "250 253 250",   # bg-gray-50
            "100": "243 250 246",  # lighter emerald/gray
            "200": "229 231 235",  # border gray-200
            "300": "209 213 219",  # subtle text gray-300
            "400": "107 114 128",  # secondary text gray-500
            "500": "31 41 55",     # primary text gray-800
            "600": "16 185 129",   # emerald-500 (main accent)
            "700": "5 150 105",    # green-600 (secondary accent)
            # Dark mode
            "800": "20 20 20",     # dark bg
            "900": "10 10 10",     # darker bg
            "950": "0 0 0",        # pure black
        },
        "primary": {
            # Light mode
            "50": "236 253 245",   # emerald-50
            "100": "209 250 229",  # emerald-100
            "200": "167 243 208",  # emerald-200
            "300": "52 211 153",   # emerald-400
            "400": "16 185 129",   # emerald-500
            "500": "5 150 105",    # green-600
            # Dark mode (emerald/green on black)
            "600": "16 185 129",   # emerald-500
            "700": "5 150 105",    # green-600
            "800": "0 0 0",        # black
            "900": "0 0 0",        # black
            "950": "0 0 0",        # black
        },
        "font": {
            "subtle-light": "var(--color-base-400)",
            "subtle-dark": "var(--color-base-400)",
            "default-light": "var(--color-base-500)",
            "default-dark": "var(--color-base-100)",
            "important-light": "var(--color-base-600)",
            "important-dark": "var(--color-primary-400)",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "User & Company",
                "icon": "people",
                "collapsible": True,
                "items": [
                    {"title": "Users", "icon": "person", "link": reverse_lazy("admin:user_auth_user_changelist")},
                    {"title": "Companies", "icon": "business", "link": reverse_lazy("admin:user_auth_company_changelist")},
                    {"title": "Roles", "icon": "security", "link": reverse_lazy("admin:user_auth_role_changelist")},
                    {"title": "Activity Logs", "icon": "history", "link": reverse_lazy("admin:user_auth_activitylog_changelist")},
                ],
            },
            {
                "title": "Accounting",
                "icon": "account_balance",
                "collapsible": True,
                "items": [
                    # Chart of Accounts
                    {"title": "Accounts", "icon": "account_tree", "link": reverse_lazy("admin:accounting_account_changelist")},
                    {"title": "Account Categories", "icon": "category", "link": reverse_lazy("admin:accounting_accountcategory_changelist")},
                    {"title": "Account Groups", "icon": "group_work", "link": reverse_lazy("admin:accounting_accountgroup_changelist")},
                    {"separator": True},
                    
                    # Journal Management
                    {"title": "Journals", "icon": "book", "link": reverse_lazy("admin:accounting_journal_changelist")},
                    {"title": "Journal Entries", "icon": "edit_note", "link": reverse_lazy("admin:accounting_journalentry_changelist")},
                    {"title": "Journal Items", "icon": "notes", "link": reverse_lazy("admin:accounting_journalitem_changelist")},
                    {"title": "Recurring Journals", "icon": "repeat", "link": reverse_lazy("admin:accounting_recurringjournal_changelist")},
                    {"separator": True},
                    
                    # Payables & Receivables
                    {"title": "Payables", "icon": "money_off", "link": reverse_lazy("admin:accounting_accountpayable_changelist")},
                    {"title": "Receivables", "icon": "attach_money", "link": reverse_lazy("admin:accounting_accountreceivable_changelist")},
                    {"separator": True},
                    
                    # Banking
                    {"title": "Bank Accounts", "icon": "account_balance_wallet", "link": reverse_lazy("admin:accounting_bankaccount_changelist")},
                    {"title": "Bank Reconciliations", "icon": "compare_arrows", "link": reverse_lazy("admin:accounting_bankreconciliation_changelist")},
                    {"separator": True},
                    
                    # Configuration & Settings
                    {"title": "Tax Configs", "icon": "percent", "link": reverse_lazy("admin:accounting_taxconfig_changelist")},
                    {"title": "Currencies", "icon": "currency_exchange", "link": reverse_lazy("admin:accounting_currency_changelist")},
                    {"separator": True},
                    
                    # Reporting & Auditing
                    {"title": "Financial Statements", "icon": "bar_chart", "link": reverse_lazy("admin:accounting_financialstatement_changelist")},
                    {"title": "Audit Logs", "icon": "history", "link": reverse_lazy("admin:accounting_accountingauditlog_changelist")},
                ],
            },
            {
                "title": "CRM & Partners",
                "icon": "contact_page",
                "collapsible": True,
                "items": [
                    # Core Partner Management
                    {"title": "Partners", "icon": "people", "link": reverse_lazy("admin:crm_partner_changelist")},
                    {"separator": True},
                    
                    # Customer Management
                    {"title": "Customers", "icon": "person", "link": reverse_lazy("admin:crm_customer_changelist")},
                    {"title": "Leads", "icon": "emoji_objects", "link": reverse_lazy("admin:crm_lead_changelist")},
                    {"title": "Opportunities", "icon": "star", "link": reverse_lazy("admin:crm_opportunity_changelist")},
                    {"separator": True},
                    
                    # Communication
                    {"title": "Communication Logs", "icon": "chat", "link": reverse_lazy("admin:crm_communicationlog_changelist")},
                ],
            },
            {
                "title": "Products",
                "icon": "inventory",
                "collapsible": True,
                "items": [
                    # Product Management
                    {"title": "Products", "icon": "inventory_2", "link": reverse_lazy("admin:products_product_changelist")},
                    {"title": "Product Categories", "icon": "category", "link": reverse_lazy("admin:products_productcategory_changelist")},
                    {"title": "Product Variants", "icon": "tune", "link": reverse_lazy("admin:products_productvariant_changelist")},
                ],
            },
            {
                "title": "Sales",
                "icon": "shopping_cart",
                "collapsible": True,
                "items": [
                    {"title": "Taxes", "icon": "percent", "link": reverse_lazy("admin:sales_tax_changelist")},
                    {
                        "separator": True,
                        "title": "Sales Process",
                    },
                    {"title": "Quotations", "icon": "description", "link": reverse_lazy("admin:sales_quotation_changelist")},
                    {"title": "Quotation Items", "icon": "list", "link": reverse_lazy("admin:sales_quotationitem_changelist")},
                    {"title": "Sales Orders", "icon": "receipt", "link": reverse_lazy("admin:sales_salesorder_changelist")},
                    {"title": "Sales Order Items", "icon": "format_list_numbered", "link": reverse_lazy("admin:sales_salesorderitem_changelist")},
                    {
                        "separator": True,
                        "title": "Invoicing & Payments",
                    },
                    {"title": "Invoices", "icon": "request_quote", "link": reverse_lazy("admin:sales_invoice_changelist")},
                    {"title": "Payments", "icon": "payments", "link": reverse_lazy("admin:sales_payment_changelist")},
                ],
            },
            {
                "title": "Purchase",
                "icon": "shopping_bag",
                "collapsible": True,
                "items": [
                    {"title": "Suppliers", "icon": "local_shipping", "link": reverse_lazy("admin:purchase_supplier_changelist")},
                    {"title": "Tax & Charges Templates", "icon": "percent", "link": reverse_lazy("admin:purchase_taxchargestemplate_changelist")},
                    {
                        "separator": True,
                        "title": "Purchase Requisitions",
                    },
                    {"title": "Purchase Requisitions", "icon": "assignment", "link": reverse_lazy("admin:purchase_purchaserequisition_changelist")},
                    {"title": "Requisition Items", "icon": "list_alt", "link": reverse_lazy("admin:purchase_purchaserequisitionitem_changelist")},
                    {
                        "separator": True,
                        "title": "RFQ & Quotations",
                    },
                    {"title": "Request For Quotations", "icon": "help_outline", "link": reverse_lazy("admin:purchase_requestforquotation_changelist")},
                    {"title": "RFQ Items", "icon": "format_list_bulleted", "link": reverse_lazy("admin:purchase_rfqitem_changelist")},
                    {"title": "Supplier Quotations", "icon": "request_quote", "link": reverse_lazy("admin:purchase_supplierquotation_changelist")},
                    {"title": "Quotation Items", "icon": "receipt_long", "link": reverse_lazy("admin:purchase_supplierquotationitem_changelist")},
                    {
                        "separator": True,
                        "title": "Purchase Orders",
                    },
                    {"title": "Purchase Orders", "icon": "shopping_cart", "link": reverse_lazy("admin:purchase_purchaseorder_changelist")},
                    {"title": "Purchase Order Items", "icon": "list", "link": reverse_lazy("admin:purchase_purchaseorderitem_changelist")},
                    {"title": "Order Tax & Charges", "icon": "calculate", "link": reverse_lazy("admin:purchase_purchaseordertaxcharge_changelist")},
                    {
                        "separator": True,
                        "title": "Goods Receipt",
                    },
                    {"title": "Goods Receipt Notes", "icon": "inventory", "link": reverse_lazy("admin:purchase_goodsreceiptnote_changelist")},
                    {"title": "GRN Items", "icon": "checklist", "link": reverse_lazy("admin:purchase_grnitem_changelist")},
                    {
                        "separator": True,
                        "title": "Bills & Payments",
                    },
                    {"title": "Purchase Bills", "icon": "receipt", "link": reverse_lazy("admin:purchase_bill_changelist")},
                    {"title": "Bill Items", "icon": "format_list_numbered", "link": reverse_lazy("admin:purchase_billitem_changelist")},
                    {"title": "Purchase Payments", "icon": "payments", "link": reverse_lazy("admin:purchase_purchasepayment_changelist")},
                    {
                        "separator": True,
                        "title": "Returns & Approvals",
                    },
                    {"title": "Purchase Returns", "icon": "keyboard_return", "link": reverse_lazy("admin:purchase_purchasereturn_changelist")},
                    {"title": "Return Items", "icon": "undo", "link": reverse_lazy("admin:purchase_purchasereturnitem_changelist")},
                    {"title": "Purchase Approvals", "icon": "approval", "link": reverse_lazy("admin:purchase_purchaseapproval_changelist")},
                ],
            },
            {
                "title": "Inventory",
                "icon": "warehouse",
                "collapsible": True,
                "items": [
                    # Setup & Configuration
                    {"title": "Warehouses", "icon": "store", "link": reverse_lazy("admin:inventory_warehouse_changelist")},
                    {"separator": True},
                    
                    # Stock Management
                    {"title": "Stock Items", "icon": "inventory_2", "link": reverse_lazy("admin:inventory_stockitem_changelist")},
                    {"title": "Stock Movements", "icon": "swap_horiz", "link": reverse_lazy("admin:inventory_stockmovement_changelist")},
                    {"separator": True},
                    
                    # Alerts & Monitoring
                    {"title": "Stock Alerts", "icon": "notification_important", "link": reverse_lazy("admin:inventory_stockalert_changelist")},
                ],
            },
            {
                "title": "HR",
                "icon": "badge",
                "collapsible": True,
                "items": [
                    # Employee Management
                    {"title": "Employees", "icon": "person", "link": reverse_lazy("admin:hr_employee_changelist")},
                    {"title": "Contractors", "icon": "engineering", "link": reverse_lazy("admin:hr_contractor_changelist")},
                    {"separator": True},
                    
                    # Time & Attendance
                    {"title": "Attendance", "icon": "event_available", "link": reverse_lazy("admin:hr_attendance_changelist")},
                    {"title": "Leaves", "icon": "beach_access", "link": reverse_lazy("admin:hr_leave_changelist")},
                    {"separator": True},
                    
                    # Payroll
                    {"title": "Payrolls", "icon": "payments", "link": reverse_lazy("admin:hr_payroll_changelist")},
                    {"title": "Payslips", "icon": "receipt", "link": reverse_lazy("admin:hr_payslip_changelist")},
                    {"separator": True},
                    
                    # Reporting
                    {"title": "HR Reports", "icon": "bar_chart", "link": reverse_lazy("admin:hr_hrreport_changelist")},
                ],
            },
            {
                "title": "Project Management",
                "icon": "assignment",
                "collapsible": True,
                "items": [
                    # Project Setup
                    {"title": "Projects", "icon": "work", "link": reverse_lazy("admin:project_mgmt_project_changelist")},
                    {"title": "Project Contractors", "icon": "groups", "link": reverse_lazy("admin:project_mgmt_projectcontractor_changelist")},
                    {"separator": True},
                    
                    # Task Management & Tracking
                    {"title": "Tasks", "icon": "task", "link": reverse_lazy("admin:project_mgmt_task_changelist")},
                    {"title": "Time Entries", "icon": "timer", "link": reverse_lazy("admin:project_mgmt_timeentry_changelist")},
                    {"separator": True},
                    
                    # Reporting
                    {"title": "Project Reports", "icon": "bar_chart", "link": reverse_lazy("admin:project_mgmt_projectreport_changelist")},
                ],
            },
            {
                "title": "Manufacturing",
                "icon": "precision_manufacturing",
                "collapsible": True,
                "items": [
                    # Bill of Materials
                    {"title": "Bill of Materials", "icon": "layers", "link": reverse_lazy("admin:manufacturing_billofmaterials_changelist")},
                    {"title": "BOM Items", "icon": "list", "link": reverse_lazy("admin:manufacturing_billofmaterialsitem_changelist")},
                    {"separator": True},
                    
                    # Production Management
                    {"title": "Work Orders", "icon": "build", "link": reverse_lazy("admin:manufacturing_workorder_changelist")},
                    {"title": "Production Plans", "icon": "event_note", "link": reverse_lazy("admin:manufacturing_productionplan_changelist")},
                    {"separator": True},
                    
                    # Subcontracting
                    {"title": "Subcontractors", "icon": "handshake", "link": reverse_lazy("admin:manufacturing_subcontractor_changelist")},
                    {"title": "Subcontract Work Orders", "icon": "assignment_turned_in", "link": reverse_lazy("admin:manufacturing_subcontractworkorder_changelist")},
                ],
            },
        ],
    },
    "EXTENSIONS": {
        "modeltranslation": {
            "flags": {
                "en": "🇬🇧",
                "fr": "🇫🇷",
                "nl": "🇧🇪",
            },
        },
    },
}
