# Generated by Django 5.2.4 on 2025-07-22 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_accountpayable_supplier_accountreceivable_customer'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_customers', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_opportunities', to='accounting.account'),
        ),
    ]
