# Generated by Django 5.2.4 on 2025-07-29 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='agreement_contract',
            field=models.FileField(blank=True, help_text='Master agreement or contract', null=True, upload_to='partners/contracts/'),
        ),
        migrations.AddField(
            model_name='partner',
            name='annual_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='bank_details',
            field=models.TextField(blank=True, help_text='Bank account details for payments'),
        ),
        migrations.AddField(
            model_name='partner',
            name='bank_documents',
            field=models.FileField(blank=True, help_text='Bank account verification documents', null=True, upload_to='partners/bank/'),
        ),
        migrations.AddField(
            model_name='partner',
            name='certifications',
            field=models.TextField(blank=True, help_text='ISO, quality certifications, etc.'),
        ),
        migrations.AddField(
            model_name='partner',
            name='compliance_documents',
            field=models.FileField(blank=True, help_text='Compliance and regulatory documents', null=True, upload_to='partners/compliance/'),
        ),
        migrations.AddField(
            model_name='partner',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Primary contact person', max_length=255),
        ),
        migrations.AddField(
            model_name='partner',
            name='credit_period_days',
            field=models.IntegerField(default=30, help_text='Credit period in days'),
        ),
        migrations.AddField(
            model_name='partner',
            name='employee_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='established_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='insurance_certificate',
            field=models.FileField(blank=True, help_text='Insurance certificate', null=True, upload_to='partners/insurance/'),
        ),
        migrations.AddField(
            model_name='partner',
            name='last_contact_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='next_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='preferred_currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('INR', 'Indian Rupee'), ('CNY', 'Chinese Yuan')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='partner',
            name='quality_certificates',
            field=models.FileField(blank=True, help_text='Quality certifications (ISO, etc.)', null=True, upload_to='partners/quality/'),
        ),
        migrations.AddField(
            model_name='partner',
            name='registration_certificate',
            field=models.FileField(blank=True, help_text='Business registration certificate', null=True, upload_to='partners/registration/'),
        ),
        migrations.AddField(
            model_name='partner',
            name='relationship_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_partners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partner',
            name='tax_certificate',
            field=models.FileField(blank=True, help_text='Tax registration certificate', null=True, upload_to='partners/tax/'),
        ),
        migrations.AddField(
            model_name='partner',
            name='vat_number',
            field=models.CharField(blank=True, help_text='VAT Registration Number', max_length=100),
        ),
        migrations.AlterField(
            model_name='partner',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company name if different from display name', max_length=255),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('company', 'Company'), ('government', 'Government'), ('non_profit', 'Non-Profit')], default='company', max_length=50),
        ),
        migrations.AlterField(
            model_name='partner',
            name='payment_terms',
            field=models.CharField(blank=True, choices=[('net_15', 'Net 15'), ('net_30', 'Net 30'), ('net_45', 'Net 45'), ('net_60', 'Net 60'), ('net_90', 'Net 90'), ('cash_on_delivery', 'Cash on Delivery'), ('advance_payment', 'Advance Payment'), ('30_60_90', '30% Advance, 70% on Delivery'), ('2_10_net_30', '2/10 Net 30'), ('custom', 'Custom Terms')], max_length=50),
        ),
        migrations.AlterField(
            model_name='partner',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Business Registration Number', max_length=50),
        ),
        migrations.AlterField(
            model_name='partner',
            name='street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='street2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Postal Code'),
        ),
    ]
