# Generated by Django 5.2.4 on 2025-08-04 04:01

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_partner_agreement_contract_partner_annual_revenue_and_more'),
        ('purchase', '0011_alter_supplier_options_remove_supplier_address_and_more'),
        ('sales', '0004_remove_invoiceitem_discount_percent_and_more'),
        ('user_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communicationlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Communication Log', 'verbose_name_plural': 'Communication Logs'},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='opportunity',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Opportunities'},
        ),
        migrations.RenameField(
            model_name='communicationlog',
            old_name='notes',
            new_name='follow_up_notes',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='close_date',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='value',
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='action_items',
            field=models.TextField(blank=True, help_text='Action items and next steps'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='actual_datetime',
            field=models.DateTimeField(blank=True, help_text='Actual date and time', null=True),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='attachments',
            field=models.FileField(blank=True, help_text='Related documents or recordings', null=True, upload_to='communications/'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Contact person on the other side', max_length=255),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_communications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='detailed_notes',
            field=models.TextField(blank=True, help_text='Detailed notes and outcomes'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='direction',
            field=models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='outbound', max_length=20),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='duration_minutes',
            field=models.IntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='follow_up_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='crm.opportunity'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='outcome',
            field=models.TextField(blank=True, help_text='Communication outcome and results'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='participants',
            field=models.TextField(blank=True, help_text='Other participants (comma-separated)'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='crm.partner'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Reference or ticket number', max_length=100),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='related_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='sales.invoice'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='related_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='sales.salesorder'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='related_quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='sales.quotation'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='scheduled_datetime',
            field=models.DateTimeField(blank=True, help_text='Scheduled date and time', null=True),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_response', 'No Response'), ('follow_up_required', 'Follow-up Required')], default='completed', max_length=50),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='summary',
            field=models.TextField(blank=True, help_text='Brief summary of communication'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='company_name',
            field=models.CharField(blank=True, help_text="Lead's company name", max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Primary contact person', max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='conversion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='converted_to_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_lead', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='lead',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated deal value', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='expected_close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='follow_up_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_contact_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_score',
            field=models.IntegerField(default=0, help_text='AI/Manual lead score (0-100)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='mobile',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='product_interest',
            field=models.TextField(blank=True, help_text='Products/services of interest'),
        ),
        migrations.AddField(
            model_name='lead',
            name='requirements',
            field=models.TextField(blank=True, help_text='Customer requirements and notes'),
        ),
        migrations.AddField(
            model_name='lead',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='street',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='actual_close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='budget_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='competitors',
            field=models.TextField(blank=True, help_text='Known competitors for this opportunity'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opportunities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='decision_timeline',
            field=models.CharField(blank=True, help_text="Customer's decision timeline", max_length=255),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='description',
            field=models.TextField(blank=True, help_text='Opportunity description and details'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='estimated_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Estimated opportunity value', max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunity',
            name='expected_close_date',
            field=models.DateField(default=datetime.date(2025, 8, 4), help_text='Expected close date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunity',
            name='industry_vertical',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='key_decision_makers',
            field=models.TextField(blank=True, help_text='Key decision makers and influencers'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='lead',
            field=models.ForeignKey(blank=True, help_text='Original lead if converted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='next_action',
            field=models.TextField(blank=True, help_text='Next action to be taken'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='next_action_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='probability',
            field=models.IntegerField(choices=[(10, '10%'), (25, '25%'), (50, '50%'), (75, '75%'), (90, '90%'), (100, '100%')], default=50, help_text='Win probability percentage'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='products_services',
            field=models.TextField(blank=True, help_text='Products/services involved in this opportunity'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='stage_history',
            field=models.JSONField(blank=True, default=list, help_text='History of stage changes'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=255),
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='crm.customer'),
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='subject',
            field=models.CharField(help_text='Communication subject/title', max_length=255),
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='type',
            field=models.CharField(choices=[('call', 'Phone Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('video_call', 'Video Call'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('chat', 'Live Chat'), ('letter', 'Letter'), ('fax', 'Fax'), ('other', 'Other')], default='call', max_length=50),
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Primary user who handled the communication', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('referral', 'Referral'), ('social_media', 'Social Media'), ('email_campaign', 'Email Campaign'), ('trade_show', 'Trade Show'), ('cold_call', 'Cold Call'), ('advertisement', 'Advertisement'), ('partner', 'Partner'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('lost', 'Lost'), ('on_hold', 'On Hold')], default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('qualification', 'Qualification'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('contract', 'Contract Review'), ('won', 'Won'), ('lost', 'Lost'), ('cancelled', 'Cancelled')], default='qualification', max_length=100),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('campaign_type', models.CharField(choices=[('email', 'Email Campaign'), ('sms', 'SMS Campaign'), ('social_media', 'Social Media'), ('trade_show', 'Trade Show'), ('webinar', 'Webinar'), ('content_marketing', 'Content Marketing'), ('advertisement', 'Advertisement'), ('cold_calling', 'Cold Calling'), ('direct_mail', 'Direct Mail'), ('other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('target_audience', models.TextField(help_text='Description of target audience')),
                ('target_segments', models.TextField(blank=True, help_text='Specific customer segments targeted')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cost_per_lead', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('target_leads', models.IntegerField(default=0, help_text='Target number of leads')),
                ('target_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('target_conversion_rate', models.DecimalField(decimal_places=2, default=0, help_text='Target conversion rate as percentage', max_digits=5)),
                ('subject_line', models.CharField(blank=True, max_length=255)),
                ('message_content', models.TextField(blank=True)),
                ('call_to_action', models.CharField(blank=True, max_length=255)),
                ('landing_page_url', models.URLField(blank=True)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('opens', models.IntegerField(default=0)),
                ('leads_generated', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_campaigns', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='user_auth.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
                ('team_members', models.ManyToManyField(blank=True, related_name='campaign_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CRMConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_stages', models.JSONField(default=list, help_text='Custom lead stages configuration')),
                ('lead_assignment_rules', models.TextField(blank=True, help_text='Lead assignment rules and criteria')),
                ('lead_scoring_rules', models.JSONField(default=dict, help_text='Lead scoring configuration')),
                ('opportunity_stages', models.JSONField(default=list, help_text='Custom opportunity pipeline stages')),
                ('default_probability_by_stage', models.JSONField(default=dict, help_text='Default probability for each stage')),
                ('customer_categories', models.JSONField(default=list, help_text='Customer categories (Retailer, Distributor, etc.)')),
                ('payment_terms_options', models.JSONField(default=list, help_text='Available payment terms')),
                ('supplier_rating_scale', models.JSONField(default=dict, help_text='Supplier rating scale and criteria')),
                ('supplier_categories', models.JSONField(default=list, help_text='Supplier categories')),
                ('email_templates', models.JSONField(default=dict, help_text='Email templates by stakeholder type')),
                ('sms_templates', models.JSONField(default=dict, help_text='SMS templates by stakeholder type')),
                ('communication_preferences', models.JSONField(default=dict, help_text='Default communication preferences')),
                ('campaign_templates', models.JSONField(default=list, help_text='Campaign templates and workflows')),
                ('automation_workflows', models.JSONField(default=list, help_text='Automation workflow configurations')),
                ('email_integration_enabled', models.BooleanField(default=False)),
                ('sms_integration_enabled', models.BooleanField(default=False)),
                ('whatsapp_integration_enabled', models.BooleanField(default=False)),
                ('voip_integration_enabled', models.BooleanField(default=False)),
                ('data_sharing_settings', models.JSONField(default=dict, help_text='Data sharing and privacy settings')),
                ('role_permissions', models.JSONField(default=dict, help_text='Custom role permissions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_config', to='user_auth.company')),
            ],
            options={
                'verbose_name': 'CRM Configuration',
                'verbose_name_plural': 'CRM Configurations',
            },
        ),
        migrations.CreateModel(
            name='SupplierRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_rating', models.DecimalField(decimal_places=1, default=0, help_text='Quality rating (0-10)', max_digits=3)),
                ('delivery_rating', models.DecimalField(decimal_places=1, default=0, help_text='Delivery performance (0-10)', max_digits=3)),
                ('price_rating', models.DecimalField(decimal_places=1, default=0, help_text='Price competitiveness (0-10)', max_digits=3)),
                ('service_rating', models.DecimalField(decimal_places=1, default=0, help_text='Service quality (0-10)', max_digits=3)),
                ('communication_rating', models.DecimalField(decimal_places=1, default=0, help_text='Communication (0-10)', max_digits=3)),
                ('overall_rating', models.DecimalField(decimal_places=1, default=0, help_text='Overall rating (0-10)', max_digits=3)),
                ('rating_period_start', models.DateField()),
                ('rating_period_end', models.DateField()),
                ('comments', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('rating_date', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_ratings', to='user_auth.company')),
                ('rated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_ratings', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='purchase.supplier')),
            ],
            options={
                'ordering': ['-rating_date'],
            },
        ),
        migrations.CreateModel(
            name='CampaignTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('opened_date', models.DateTimeField(blank=True, null=True)),
                ('clicked_date', models.DateTimeField(blank=True, null=True)),
                ('responded_date', models.DateTimeField(blank=True, null=True)),
                ('converted_date', models.DateTimeField(blank=True, null=True)),
                ('response_type', models.CharField(blank=True, max_length=50)),
                ('response_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='crm.campaign')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_targets', to='crm.customer')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_targets', to='crm.lead')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_targets', to='crm.partner')),
            ],
            options={
                'unique_together': {('campaign', 'lead', 'customer', 'partner')},
            },
        ),
    ]
