# Generated by Django 5.2.4 on 2026-08-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_enhanced_crm_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cnic',
            field=models.CharField(blank=True, help_text='National ID (optional)', max_length=20),
        ),
    ]
