# Generated by Django 5.2.4 on 2026-08-02 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_customer_cnic'),
        ('user_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('reference_type', models.CharField(choices=[('invoice', 'Sales Invoice'), ('payment', 'Payment Received'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note'), ('advance', 'Advance Payment'), ('adjustment', 'Manual Adjustment'), ('opening_balance', 'Opening Balance')], max_length=50)),
                ('reference_id', models.IntegerField(help_text='ID of the referenced document')),
                ('description', models.TextField()),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount owed BY customer (invoice)', max_digits=15)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount paid BY customer', max_digits=15)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Running balance', max_digits=15)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_ledgers', to='user_auth.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='crm.customer')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['customer', 'transaction_date'], name='crm_custome_custome_4ddbf4_idx'), models.Index(fields=['reference_type', 'reference_id'], name='crm_custome_referen_d3b991_idx')],
            },
        ),
    ]
