# Generated by Django 5.2.4 on 2026-08-11 01:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_customerledgeradjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerledgeradjustment',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
