# Generated by Django 5.2.4 on 2026-08-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_customerledgeradjustment_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierrating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierrating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
