# Generated by Django 5.2.4 on 2026-08-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_supplierrating_created_at_supplierrating_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerledger',
            name='reference_id',
            field=models.BigIntegerField(help_text='ID of the referenced document'),
        ),
    ]
