# Generated by Django 5.2.4 on 2025-08-05 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoJournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_module', models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('inventory', 'Inventory'), ('manufacturing', 'Manufacturing'), ('hr', 'HR'), ('crm', 'CRM'), ('project', 'Project'), ('accounting', 'Accounting')], max_length=20)),
                ('source_model', models.CharField(max_length=100)),
                ('source_object_id', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.TextField(blank=True)),
                ('is_reversed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_journal_entries', to='user_auth.company')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_entries', to='accounting.journalentry')),
            ],
            options={
                'verbose_name': 'Auto Journal Entry',
                'verbose_name_plural': 'Auto Journal Entries',
            },
        ),
        migrations.CreateModel(
            name='ModuleAccountMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('sales_invoice', 'Sales Invoice'), ('sales_return', 'Sales Return'), ('sales_discount', 'Sales Discount'), ('purchase_invoice', 'Purchase Invoice'), ('purchase_return', 'Purchase Return'), ('purchase_discount', 'Purchase Discount'), ('inventory_receipt', 'Inventory Receipt'), ('inventory_issue', 'Inventory Issue'), ('inventory_adjustment', 'Inventory Adjustment'), ('inventory_transfer', 'Inventory Transfer'), ('material_issue', 'Material Issue to Production'), ('production_completion', 'Production Completion'), ('work_order_cost', 'Work Order Cost'), ('manufacturing_overhead', 'Manufacturing Overhead'), ('payroll_salary', 'Payroll Salary'), ('payroll_bonus', 'Payroll Bonus'), ('employee_advance', 'Employee Advance'), ('employee_expense', 'Employee Expense'), ('customer_invoice', 'Customer Invoice'), ('customer_payment', 'Customer Payment'), ('customer_refund', 'Customer Refund'), ('project_expense', 'Project Expense'), ('project_billing', 'Project Billing'), ('project_cost', 'Project Cost'), ('bank_payment', 'Bank Payment'), ('bank_receipt', 'Bank Receipt'), ('cash_payment', 'Cash Payment'), ('cash_receipt', 'Cash Receipt')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_account_mappings', to='user_auth.company')),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_mappings', to='accounting.account')),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_mappings', to='accounting.account')),
            ],
            options={
                'verbose_name': 'Module Account Mapping',
                'verbose_name_plural': 'Module Account Mappings',
                'unique_together': {('company', 'transaction_type')},
            },
        ),
    ]
