# Generated by Django 5.2.4 on 2025-08-05 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_autojournalentry_moduleaccountmapping'),
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autojournalentry',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='autojournalentry',
            name='description',
        ),
        migrations.RemoveField(
            model_name='autojournalentry',
            name='is_reversed',
        ),
        migrations.AlterField(
            model_name='autojournalentry',
            name='journal_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_entry', to='accounting.journalentry'),
        ),
        migrations.AlterField(
            model_name='autojournalentry',
            name='source_module',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='moduleaccountmapping',
            name='transaction_type',
            field=models.CharField(choices=[('sales_invoice', 'Sales Invoice'), ('sales_return', 'Sales Return'), ('sales_discount', 'Sales Discount'), ('purchase_invoice', 'Purchase Invoice'), ('purchase_return', 'Purchase Return'), ('purchase_discount', 'Purchase Discount'), ('inventory_receipt', 'Inventory Receipt'), ('inventory_issue', 'Inventory Issue'), ('inventory_adjustment', 'Inventory Adjustment'), ('inventory_transfer', 'Inventory Transfer'), ('material_issue', 'Material Issue to Production'), ('production_completion', 'Production Completion'), ('work_order_cost', 'Work Order Cost'), ('manufacturing_overhead', 'Manufacturing Overhead'), ('payroll_salary', 'Payroll Salary'), ('payroll_bonus', 'Payroll Bonus'), ('employee_advance', 'Employee Advance'), ('employee_expense', 'Employee Expense'), ('customer_invoice', 'Customer Invoice'), ('customer_payment', 'Customer Payment'), ('project_expense', 'Project Expense'), ('project_billing', 'Project Billing'), ('bank_transfer', 'Bank Transfer'), ('cash_receipt', 'Cash Receipt'), ('cash_payment', 'Cash Payment')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='autojournalentry',
            index=models.Index(fields=['source_module', 'source_model', 'source_object_id'], name='accounting__source__c23ed0_idx'),
        ),
        migrations.AddIndex(
            model_name='autojournalentry',
            index=models.Index(fields=['transaction_type'], name='accounting__transac_aa30e6_idx'),
        ),
    ]
