# Generated by Django 5.2.4 on 2025-08-07 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_remove_autojournalentry_amount_and_more'),
        ('user_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconciliation_date', models.DateField()),
                ('statement_date', models.DateField()),
                ('statement_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('book_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='accounting.account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Reconciliation',
                'verbose_name_plural': 'Account Reconciliations',
            },
        ),
        migrations.CreateModel(
            name='AccountTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('retail', 'Retail Business'), ('manufacturing', 'Manufacturing'), ('service', 'Service Business'), ('consulting', 'Consulting'), ('restaurant', 'Restaurant/Food Service'), ('healthcare', 'Healthcare'), ('construction', 'Construction'), ('nonprofit', 'Non-Profit'), ('ecommerce', 'E-Commerce'), ('custom', 'Custom Template')], max_length=20)),
                ('description', models.TextField()),
                ('is_system', models.BooleanField(default=True, help_text='System template vs custom template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Template',
                'verbose_name_plural': 'Account Templates',
            },
        ),
        migrations.CreateModel(
            name='COASettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_format', models.CharField(choices=[('numeric', 'Numeric'), ('alphanumeric', 'Alphanumeric'), ('hierarchical', 'Hierarchical'), ('custom', 'Custom')], default='numeric', max_length=20)),
                ('code_length', models.CharField(default='4', max_length=10)),
                ('custom_pattern', models.CharField(blank=True, max_length=50)),
                ('auto_generate_codes', models.BooleanField(default=True)),
                ('strict_code_validation', models.BooleanField(default=True)),
                ('default_view', models.CharField(default='list', max_length=20)),
                ('accounts_per_page', models.CharField(default='50', max_length=10)),
                ('show_account_codes', models.BooleanField(default=True)),
                ('show_balances', models.BooleanField(default=True)),
                ('color_coding', models.BooleanField(default=True)),
                ('hierarchical_indent', models.BooleanField(default=True)),
                ('require_approval_new_accounts', models.BooleanField(default=False)),
                ('restrict_account_deletion', models.BooleanField(default=True)),
                ('log_account_changes', models.BooleanField(default=True)),
                ('log_balance_changes', models.BooleanField(default=True)),
                ('auto_sales_entries', models.BooleanField(default=True)),
                ('auto_purchase_entries', models.BooleanField(default=True)),
                ('auto_inventory_entries', models.BooleanField(default=True)),
                ('auto_backup_enabled', models.BooleanField(default=False)),
                ('backup_frequency', models.CharField(default='weekly', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coa_settings', to='user_auth.company')),
                ('default_inventory_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_inventory', to='accounting.account')),
                ('default_purchase_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_purchase', to='accounting.account')),
                ('default_sales_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_sales', to='accounting.account')),
            ],
            options={
                'verbose_name': 'COA Settings',
                'verbose_name_plural': 'COA Settings',
            },
        ),
        migrations.CreateModel(
            name='ImportExportOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('import', 'Import'), ('export', 'Export')], max_length=10)),
                ('data_type', models.CharField(choices=[('accounts', 'Accounts'), ('groups', 'Account Groups'), ('chart', 'Chart of Accounts'), ('template', 'Account Template')], max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_format', models.CharField(blank=True, max_length=10)),
                ('record_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import/Export Operation',
                'verbose_name_plural': 'Import/Export Operations',
            },
        ),
        migrations.CreateModel(
            name='AccountTemplateAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('income', 'Income'), ('expense', 'Expense'), ('contra', 'Contra-Account')], max_length=20)),
                ('balance_side', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('group_code', models.CharField(blank=True, max_length=20)),
                ('parent_code', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_accounts', to='accounting.accounttemplate')),
            ],
            options={
                'unique_together': {('template', 'code')},
            },
        ),
        migrations.CreateModel(
            name='AccountTemplateGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('category_name', models.CharField(max_length=50)),
                ('parent_code', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_groups', to='accounting.accounttemplate')),
            ],
            options={
                'unique_together': {('template', 'code')},
            },
        ),
    ]
