# Generated by Django 5.2.4 on 2025-08-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesorderdiscount_salesorderitemtracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='discount_percent',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='delivery_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percentage'), ('amount', 'Amount')], default='percent', max_length=10),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='quality_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='tracking_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='tracking_data',
            field=models.JSONField(blank=True, default=list, help_text='Tracking numbers, serial numbers, batch info'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='tracking_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='uom',
            field=models.CharField(default='Pcs', help_text='Unit of Measure', max_length=20),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percentage'), ('amount', 'Amount')], default='percent', max_length=10),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='tracking_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='tracking_data',
            field=models.JSONField(blank=True, default=list, help_text='Tracking numbers, serial numbers, batch info'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='tracking_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='uom',
            field=models.CharField(default='Pcs', help_text='Unit of Measure', max_length=20),
        ),
    ]
