# Generated by Django 5.2.4 on 2026-08-02 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_brand_producttracking_battery_health_and_more'),
        ('sales', '0004_remove_invoiceitem_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='tracking_unit',
            field=models.ForeignKey(blank=True, help_text='Specific IMEI/serial unit sold on this line (POS explicit selection) - when set, this exact unit is sold instead of FIFO-picking any available unit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='products.producttracking'),
        ),
    ]
