# Generated by Django 5.2.4 on 2026-08-05 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_brand_producttracking_battery_health_and_more'),
        ('sales', '0005_invoiceitem_tracking_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='sales.currency'),
        ),
        migrations.CreateModel(
            name='CreditNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.creditnote')),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='sales.invoiceitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_note_items', to='products.product')),
                ('tracking_unit', models.ForeignKey(blank=True, help_text='Specific IMEI/serial unit being returned - null for untracked/quantity-based items', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_note_items', to='products.producttracking')),
            ],
        ),
    ]
