# Generated by Django 5.2.4 on 2026-08-06 02:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_creditnote_currency_creditnoteitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='credit_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
