# Generated by Django 5.2.4 on 2026-08-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_invoice_deleted_at_invoice_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='discounts',
            field=models.JSONField(blank=True, default=list, help_text='[{"type": "fixed"|"percent"|"per_unit", "value": "10.00"}, ...]'),
        ),
    ]
