# Generated by Django 5.2.4 on 2026-08-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_invoiceitem_discounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('percent', 'Percent')], default='fixed', help_text='How discount_amount is interpreted - a flat currency figure, or a percentage of the subtotal', max_length=10),
        ),
    ]
