# Generated by Django 5.2.4 on 2025-07-28 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_stockalert_options_alter_stockitem_options_and_more'),
        ('products', '0002_product_default_variant_product_is_variant_and_more'),
        ('purchase', '0005_remove_bill_account_remove_purchaseorder_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producttracking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_batch_tracking',
            field=models.BooleanField(default=False, help_text='Whether this product should be tracked by batch/lot numbers'),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_expiry_tracking',
            field=models.BooleanField(default=False, help_text='Whether this product has expiry dates that need tracking'),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_individual_tracking',
            field=models.BooleanField(default=False, help_text='Whether each unit must be tracked individually (for serial/IMEI)'),
        ),
        migrations.AddField(
            model_name='product',
            name='shelf_life_days',
            field=models.IntegerField(blank=True, help_text='Shelf life in days (for expiry tracking)', null=True),
        ),
        migrations.AddField(
            model_name='producttracking',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producttracking',
            name='current_warehouse',
            field=models.ForeignKey(blank=True, help_text='Current warehouse location', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='producttracking',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Additional custom tracking fields'),
        ),
        migrations.AddField(
            model_name='producttracking',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producttracking',
            name='grn_item',
            field=models.ForeignKey(blank=True, help_text='GRN item this tracking unit came from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_tracking_units', to='purchase.grnitem'),
        ),
        migrations.AddField(
            model_name='producttracking',
            name='location_notes',
            field=models.CharField(blank=True, help_text='Specific location within warehouse', max_length=255),
        ),
        migrations.AddField(
            model_name='producttracking',
            name='manufacturing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producttracking',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='producttracking',
            name='quality_status',
            field=models.CharField(choices=[('pending', 'Pending Inspection'), ('passed', 'Quality Passed'), ('failed', 'Quality Failed'), ('quarantined', 'Quarantined')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='producttracking',
            name='service_history',
            field=models.TextField(blank=True, help_text='Service and maintenance history'),
        ),
        migrations.AddField(
            model_name='producttracking',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('returned', 'Returned'), ('damaged', 'Damaged'), ('expired', 'Expired'), ('quarantined', 'Quarantined')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='producttracking',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.supplier'),
        ),
        migrations.AddField(
            model_name='producttracking',
            name='supplier_batch_reference',
            field=models.CharField(blank=True, help_text="Supplier's batch reference", max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='tracking_method',
            field=models.CharField(choices=[('none', 'No Tracking'), ('batch', 'Batch/Lot Tracking'), ('serial', 'Serial Number'), ('imei', 'IMEI Number'), ('barcode', 'Barcode Tracking'), ('expiry', 'Expiry Date Tracking')], default='none', help_text='How this product is tracked individually', max_length=20),
        ),
        migrations.AlterField(
            model_name='producttracking',
            name='imei_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='producttracking',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='producttracking',
            index=models.Index(fields=['serial_number'], name='products_pr_serial__3c6057_idx'),
        ),
        migrations.AddIndex(
            model_name='producttracking',
            index=models.Index(fields=['imei_number'], name='products_pr_imei_nu_7c48ac_idx'),
        ),
        migrations.AddIndex(
            model_name='producttracking',
            index=models.Index(fields=['barcode'], name='products_pr_barcode_4bd56a_idx'),
        ),
        migrations.AddIndex(
            model_name='producttracking',
            index=models.Index(fields=['batch_number'], name='products_pr_batch_n_9aeb6a_idx'),
        ),
        migrations.AddIndex(
            model_name='producttracking',
            index=models.Index(fields=['status'], name='products_pr_status_4a27cc_idx'),
        ),
        migrations.AddIndex(
            model_name='producttracking',
            index=models.Index(fields=['expiry_date'], name='products_pr_expiry__7ec27e_idx'),
        ),
        migrations.RemoveField(
            model_name='producttracking',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='producttracking',
            name='is_available',
        ),
    ]
