# Generated by Django 5.2.4 on 2025-08-02 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventorylock_options_and_more'),
        ('products', '0003_alter_producttracking_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auto_reorder',
            field=models.BooleanField(default=False, help_text='Auto-create purchase requisitions'),
        ),
        migrations.AddField(
            model_name='product',
            name='bill_of_materials',
            field=models.JSONField(blank=True, help_text='BOM for manufacturing', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='default_purchase_warehouse',
            field=models.ForeignKey(blank=True, help_text='Default warehouse for purchases', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_purchase_products', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='product',
            name='default_sales_warehouse',
            field=models.ForeignKey(blank=True, help_text='Default warehouse for sales', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_sales_products', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='product',
            name='lead_time_days',
            field=models.IntegerField(default=0, help_text='Procurement lead time in days'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturing_type',
            field=models.CharField(blank=True, choices=[('make_to_stock', 'Make to Stock'), ('make_to_order', 'Make to Order'), ('engineer_to_order', 'Engineer to Order')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quality_parameters',
            field=models.TextField(blank=True, help_text='Quality check parameters'),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_quality_inspection',
            field=models.BooleanField(default=False, help_text='Requires QC before use'),
        ),
        migrations.AddField(
            model_name='product',
            name='safety_stock',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Safety stock level', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='valuation_method',
            field=models.CharField(choices=[('fifo', 'First In First Out'), ('lifo', 'Last In First Out'), ('weighted_avg', 'Weighted Average'), ('standard', 'Standard Cost'), ('landed_cost', 'Landed Cost')], default='weighted_avg', help_text='Default valuation method for inventory', max_length=20),
        ),
    ]
