# Generated by Django 5.2.4 on 2026-08-02 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_customer_cnic'),
        ('products', '0004_product_auto_reorder_product_bill_of_materials_and_more'),
        ('sales', '0004_remove_invoiceitem_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, help_text='e.g. Samsung, Apple - same brand/model is shared across vendors, not duplicated per-vendor', max_length=100),
        ),
        migrations.AddField(
            model_name='producttracking',
            name='battery_health',
            field=models.PositiveIntegerField(blank=True, help_text='Battery health percentage', null=True),
        ),
        migrations.AddField(
            model_name='producttracking',
            name='pta_status',
            field=models.CharField(blank=True, choices=[('approved', 'PTA Approved'), ('non_approved', 'Non-PTA'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='producttracking',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Per-unit price override (falls back to Product.selling_price if unset)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='producttracking',
            name='sold_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producttracking',
            name='sold_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_tracking_units', to='sales.invoice'),
        ),
        migrations.AddField(
            model_name='producttracking',
            name='sold_to_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_tracking_units', to='crm.partner'),
        ),
        migrations.AddField(
            model_name='producttracking',
            name='storage_capacity',
            field=models.CharField(blank=True, help_text='e.g. 128GB, 256GB', max_length=20),
        ),
    ]
