# Generated by Django 5.2.4 on 2026-08-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_brand_producttracking_battery_health_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock Keeping Unit - auto-generated if left blank', max_length=100, unique=True),
        ),
    ]
