# Generated by Django 5.2.4 on 2026-08-08 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_deleted_at_product_deleted_by_and_more'),
        ('purchase', '0015_bill_discount_amount_billitem_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttracking',
            name='bill_item',
            field=models.ForeignKey(blank=True, help_text='Bill (vendor invoice) line this unit was received against - set by bill_receive_items(), the manual-bill receiving flow this shop uses.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_tracking_units', to='purchase.billitem'),
        ),
    ]
