# Generated by Django 5.2.4 on 2026-08-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_producttracking_bill_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
